### ISSUE TITLE
貌似不起作用诶

### ISSUE THREAD

**Issue by shirakun** [YourRansom/YourRansom#1]
![image](https://cloud.githubusercontent.com/assets/11274807/26817733/52302708-4aca-11e7-80bb-c23fec3f0a1e.png)
编译前啥都没改,直接编译运行的,管理员权限也试过了
改了配置文件之后编译的话直接闪退了

**Comment by popu125** [comment]
大概是某些配置有问题，我在准备写个一键脚本。。。造(bao)福(fu)大(she)众(hui)

**Comment by popu125** [comment]
@shirakun 脚本已经完成，请上车 https://bobiji.com/post/yr1k/
